set dotenv-load := true
set positional-arguments

help:
    @just --list --unsorted

build:
    cargo build
alias b := build

test *ARGS:
    cargo test "$@"

check:
    cargo check
alias c := check

fix:
    cargo clippy --fix
