set dotenv-load := true
set positional-arguments

help:
    @just --list --unsorted

build *ARGS:
    cargo build "$@"
alias b := build

check:
    cargo check
alias c := check

fix:
    cargo clippy --fix

run *ARGS:
    cargo run --example actix --features actix

test:
    #cargo test "$@"
    cargo test --features actix "$@"
alias r := run