name: test

on:
  push:
    branches:
    - '**'
  pull_request:
    branches:
    - master


defaults:
  run:
    shell: bash


jobs:
  run-test:
    permissions:
      contents: read
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        # stable (1.70) appears to have been released with a regression that impacts aarch64-unknown-linux-musl
        # It appears to primarily impact macro crates, as that's when the compilation fails here,
        # and the Github issue also mentions it failing in a macro crate.
        # See:
        # https://github.com/rust-lang/rust/issues/113104
        # https://github.com/rust-lang/rust/issues/111888
        # Fix the toolchain until those are fixed
        toolchain: 1.67
    - uses: Swatinem/rust-cache@v1
    - run: cargo install just
    - run: just test